version: '3'

services:
  loadbalancer:
    image: dockercloud/haproxy
    depends_on:
      - waf
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - web
    deploy:
      placement:
        constraints: [node.role == manager]

  waf:
   image: waf
   expose: 
     - "8080"
   environment:
     - SERVICE_PORTS=8080
   depends_on:
     - app
   deploy:
     replicas: 3
     update_config:
       parallelism: 1
       delay: 10s
     restart_policy:
       condition: on-failure
       max_attempts: 3
       window: 120s
   networks:
     - web

  app:
   image: app
   ports: 
     - "9090:9090"
   networks:
     - web

networks:
  web:
    driver: overlay
